all: 
	g++ -std=c++11 \
	-I/home/filipecn/ClionProjects/Aergia/src \
	-I/home/filipecn/ClionProjects/Aergia/src/GUI \
	-I/home/filipecn/ClionProjects/Aergia/src/GUI/UI \
	-I/home/filipecn/ClionProjects/Aergia/src/GUI/Graphics \
	-I/home/filipecn/ClionProjects/Aergia/src/Common \
	-I/home/filipecn/ClionProjects/Aergia/src/Graphics \
	-I/home/filipecn/ClionProjects/Aergia/src/Graphics/Rendering \
	-I/home/filipecn/ClionProjects/Aergia/src/Graphics/Helpers \
	-I/home/filipecn/ClionProjects/Aergia/src/Graphics/Scene \
	-I/home/filipecn/ClionProjects/Aergia/src/Math \
	-I/home/filipecn/ClionProjects/Aergia/src/IO \
	-I/home/filipecn/ClionProjects/Aergia/src/IO/Resources \
	-I/usr/local/include/GLFW \
	main.cpp \
	-L/home/filipecn/ClionProjects/Aergia/build -lAergia \
	-lglfw3  -lGL -lGLU -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lm -lXext -lGLEW -lXmu \
	-L/usr/local/lib -lSOIL
